import { CATEGORY } from './enums';

// Central UI copy used across pages and components — edit display text here,
// in one place, instead of hunting through the JSX. Dynamic messages are
// functions that take the values they interpolate.
export const STRINGS = {
  common: {
    logIn: 'Log In',
    startShopping: 'Start Shopping',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    freeShipping: 'Free',
    buyOnEtsy: 'Buy on Etsy',
    loaderDefault: 'Polishing the silver…',
    loginToWishlist: 'Please log in to save to wishlist',
    welcomeBack: (name) => `Welcome back, ${name}!`,
  },

  header: {
    announcement: 'Currently We accept ordrs from etsy only;',
    logoAlt: 'Rijisha Atelier — Handcrafted Elegance, Timelessly Yours',
    navHome: 'Home',
    navShop: 'Shop',
    navAdmin: 'Admin',
    hello: (name) => `Hi, ${name}`,
    loggedOut: 'You have been logged out',
  },

  footer: {
    about: 'Handcrafted 925 sterling silver earrings and necklaces — designed to be worn every day and treasured forever.',
    shopTitle: 'Shop',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    accountTitle: 'Account',
    myWishlist: 'My Wishlist',
    etsyShop: 'Our Etsy Shop',
    loginRegister: 'Login / Register',
    contactTitle: 'Contact Us',
    address: <>Rijisha Jewellers, MG Road,<br />Kochi, Kerala 682016</>,
    phone: '+91 98765 43210',
    email: 'hello@rijishajewellers.com',
    copyright: '© 2026 Rijisha Jewellers. All rights reserved.',
    tagline: 'Handcrafted with ♥ in India',
  },

  home: {
    heroEyebrow: 'Handcrafted 925 Sterling Silver',
    heroTitle: <>Where Silver<br />Becomes <em>Poetry</em></>,
    heroText: 'Discover earrings and necklaces sculpted by master artisans — timeless silver jewellery designed to make every moment shine.',
    heroCtaShop: 'Shop Collection',
    heroCtaStory: 'Our Story',
    heroStats: [
      { value: '92.5%', label: 'Pure Silver' },
      { value: '5,000+', label: 'Happy Customers' },
      { value: '100%', label: 'Hallmarked' },
    ],
    heroVideoAria: 'Model flaunting Rijisha silver jewellery',
    collectionsEyebrow: 'Curated For You',
    collectionsTitle: 'Shop by Collection',
    collectionsText: 'Four signatures, one promise — silver that speaks softly and shines forever.',
    collectionSub: {
      [CATEGORY.EARRINGS]: 'Jhumkas · Hoops · Studs · Drops',
      [CATEGORY.NECKLACES]: 'Pendants · Chokers · Layered Chains',
      [CATEGORY.BRACELETS]: 'Bangles · Kadas · Charm Chains',
      [CATEGORY.ANTIQUE]: 'Anklets · Maang Tikkas · More',
    },
    comingSoonBadge: 'Coming Soon',
    comingSoonSub: 'Launching Soon · Stay Tuned',
    collectionAlt: (title) => `${title} collection`,
    featuredEyebrow: 'Bestsellers',
    featuredTitle: 'Our Signature Pieces',
    featuredText: 'Loved, reviewed and re-ordered — straight from the Rijisha atelier.',
    featuredLoader: 'Bringing out the bestsellers…',
    viewAll: 'View All Pieces',
    promises: [
      { title: '925 Sterling Silver', sub: 'BIS hallmarked purity' },
      { title: 'Free Shipping', sub: 'On orders above ₹2,999' },
      { title: '15-Day Easy Returns', sub: 'No questions asked' },
      { title: 'Anti-Tarnish Finish', sub: 'Shine that stays' },
    ],
    storyEyebrow: 'Our Story',
    storyTitle: <>Crafted by Hand,<br />Cherished for Generations</>,
    storyText1: 'Rijisha Jewellers began as a small family atelier with one belief — that silver is not just a metal, but a memory in the making. Every piece we create carries the warmth of the hands that shaped it.',
    storyText2: 'Today, our master artisans blend traditional Indian karigari with contemporary design, creating earrings and necklaces that feel as personal as they look precious.',
    storyPoints: [
      'Handcrafted by third-generation silversmiths',
      'Ethically sourced, 92.5% pure sterling silver',
      'Every piece BIS hallmarked & quality checked',
    ],
    storyCta: 'Explore the Craft',
    testimonialsEyebrow: 'Words of Love',
    testimonialsTitle: 'What Our Customers Say',
    testimonialsText: 'Over 5,000 happy customers across India trust Rijisha for their silver moments.',
    testimonials: [
      {
        quote: '"The Meera Jhumkas are even more beautiful in person. The finish is flawless and they\'re so light I forget I\'m wearing them."',
        initials: 'AS',
        name: 'Ananya Sharma',
        city: 'Mumbai',
      },
      {
        quote: '"Bought the Tara layered necklace for my sister\'s wedding. Everyone asked where it was from. Packaging felt like a gift itself!"',
        initials: 'PR',
        name: 'Priya Raghavan',
        city: 'Bengaluru',
      },
      {
        quote: '"Six months of daily wear and my hoops still shine like day one. The anti-tarnish coating truly works. Fully worth it."',
        initials: 'MK',
        name: 'Meghna Kapoor',
        city: 'Delhi',
      },
    ],
  },

  shop: {
    eyebrow: 'The Collection',
    title: 'Shop Silver Jewellery',
    text: 'Every piece handcrafted in 92.5% sterling silver with an anti-tarnish finish.',
    allPieces: 'All Pieces',
    searchPlaceholder: 'Search jewellery...',
    sortFeatured: 'Featured',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortRating: 'Top Rated',
    sortNewest: 'Newest',
    soonPill: 'Coming Soon',
    soonTitle: 'Bracelets are on their way',
    soonText: 'Our artisans are crafting the very first Rijisha bracelet collection right now. Stay tuned — it will be worth the wait.',
    browseOther: 'Browse Other Pieces',
    loader: 'Laying out the collection…',
    noMatch: 'No pieces match your search.',
  },

  productCard: {
    addedToWishlist: (name) => `♥ ${name} added to wishlist`,
    removedFromWishlist: (name) => `${name} removed from wishlist`,
  },

  productDetail: {
    backToShop: 'Back to Shop',
    loader: 'Unveiling this piece…',
    crumbHome: 'Home',
    reviews: (rating, count) => `${rating} · ${count} reviews`,
    discountOff: (pct) => `${pct}% off`,
    taxNote: 'Inclusive of all taxes · Free shipping above ₹2,999',
    points: [
      '92.5% pure sterling silver, BIS hallmarked',
      'Anti-tarnish e-coating for lasting shine',
      'Ships in premium gift packaging',
    ],
    onlyLeft: (n) => `Only ${n} left in stock`,
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    addedToWishlist: '♥ Added to wishlist',
    removedFromWishlist: 'Removed from wishlist',
  },

  cart: {
    emptyTitle: 'Your bag is empty',
    emptyText: 'Beautiful silver is waiting for you.',
    eyebrow: 'Your Bag',
    title: 'Shopping Bag',
    shipHint: (amount) => `Add ${amount} more for free shipping`,
    proceed: 'Proceed to Checkout',
    continueShopping: '← Continue shopping',
  },

  checkout: {
    loginTitle: 'Please log in to checkout',
    loginText: 'Your bag is saved — log in or create an account to place your order.',
    emptyTitle: 'Your bag is empty',
    eyebrow: 'Almost There',
    title: 'Checkout',
    shippingDetails: 'Shipping Details',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Your full name',
    phone: 'Phone',
    phonePlaceholder: '10-digit mobile number',
    phoneHint: 'Enter a 10-digit phone number',
    address: 'Address',
    addressPlaceholder: 'House no., street, area',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    pincodePlaceholder: '6-digit pincode',
    pincodeHint: 'Enter a 6-digit pincode',
    paymentMethod: 'Payment Method',
    codTitle: 'Cash on Delivery',
    codText: 'Pay when your order arrives',
    upiTitle: 'UPI',
    upiText: 'Pay on delivery via UPI',
    placing: 'Placing Order…',
    placeOrder: (amount) => `Place Order · ${amount}`,
    orderPlaced: '✓ Order placed successfully!',
  },

  orders: {
    loginTitle: 'Log in to see your orders',
    eyebrow: 'Your Account',
    title: 'My Orders',
    loader: 'Fetching your orders…',
    empty: "You haven't placed any orders yet.",
    orderNo: (id) => `Order #${id}`,
    shipsTo: (method, city, state, pincode) => `${method} · Ships to ${city}, ${state} ${pincode}`,
    total: (amount) => `Total: ${amount}`,
  },

  wishlist: {
    loginTitle: 'Log in to see your wishlist',
    loginText: 'Save the pieces you love and find them here anytime.',
    eyebrow: 'Saved With Love',
    title: 'My Wishlist',
    loader: 'Gathering your favourites…',
    empty: 'Nothing saved yet — tap the ♥ on any piece you love.',
    browse: 'Browse Pieces',
  },

  login: {
    eyebrow: 'Welcome Back',
    title: 'Log In',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    passwordPlaceholder: 'Your password',
    busy: 'Logging in…',
    switchText: 'New to Rijisha?',
    switchLink: 'Create an account',
  },

  register: {
    eyebrow: 'Join Us',
    title: 'Create Account',
    name: 'Full Name',
    namePlaceholder: 'Your name',
    passwordPlaceholder: 'At least 6 characters',
    busy: 'Creating account…',
    switchText: 'Already have an account?',
    switchLink: 'Log in',
    welcome: (name) => `Welcome to Rijisha, ${name}!`,
  },

  adminLogin: {
    eyebrow: 'Store Management',
    title: 'Admin Login',
    email: 'Admin Email',
    emailPlaceholder: 'admin@rijisha.com',
    passwordPlaceholder: 'Admin password',
    submit: 'Log In as Admin',
    note: 'This portal is for store administrators only.',
  },

  admin: {
    viewStore: '← View Store',
    signedInAs: (email) => `Signed in as ${email}`,
    logOut: 'Log Out',
    eyebrow: 'Store Management',
    title: 'Admin Panel',
    subtitle: 'Add, edit or remove pieces — changes appear on the shop instantly.',
    homepageMedia: 'Homepage Media',
    homepageMediaHint: 'Control what visitors see first — the hero video at the top of the home page and the photos on the four "Shop by Collection" cards. Reset anything to bring back its built-in default.',
    heroLabel: 'Hero Video — top of the home page',
    heroHelp: 'This video plays inside the arched frame of the hero section. A vertical (portrait) video looks best — mp4, webm or mov, up to 50 MB. Keep it short and seamless; it loops silently.',
    defaultTag: 'Default',
    uploading: 'Uploading…',
    changeVideo: 'Change Video',
    uploadVideo: 'Upload Video',
    resetToDefault: 'Reset to Default',
    collectionCardsLabel: 'Shop by Collection — card photos',
    changePhoto: 'Change Photo',
    uploadPhoto: 'Upload Photo',
    reset: 'Reset',
    editProduct: 'Edit Product',
    addNewProduct: 'Add New Product',
    nameLabel: 'Name *',
    namePlaceholder: 'e.g. Riya Silver Studs',
    categoryLabel: 'Category *',
    subCategoryLabel: 'Sub-category',
    subCategoryPlaceholder: 'e.g. Studs, Jhumka, Pendant',
    priceLabel: 'Price (₹) *',
    pricePlaceholder: '2499',
    mrpLabel: 'MRP (₹, for showing a discount)',
    mrpPlaceholder: '3199 (optional)',
    stockLabel: 'Stock',
    tagLabel: 'Tag',
    tagNone: 'None',
    mediaLabel: 'Photos & Videos (you can select multiple)',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Tell customers what makes this piece special...',
    artStyleLabel: 'If no photo: illustration style',
    cardBackgroundLabel: 'Card background',
    previewLabel: 'Preview',
    mediaListLabel: (count) => `Product media (${count}) — the first photo is used as the thumbnail`,
    mediaNewTag: 'new',
    saving: 'Saving…',
    saveChanges: 'Save Changes',
    addProduct: 'Add Product',
    cancelEdit: 'Cancel Edit',
    allProducts: (count) => `All Products (${count})`,
    thName: 'Name',
    thCategory: 'Category',
    thPrice: 'Price',
    thStock: 'Stock',
    thTag: 'Tag',
    thActions: 'Actions',
    noTag: '—',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: (name) => `Delete "${name}"? This cannot be undone.`,
    productUpdated: '✓ Product updated',
    productAdded: '✓ Product added — it is live on the shop now',
    productDeleted: (name) => `${name} deleted`,
    heroUpdated: '✓ Hero video updated — it is live on the home page',
    photoUpdated: '✓ Collection photo updated — it is live on the home page',
    heroReset: 'Hero is back to the default video',
    cardReset: 'Card is back to its default illustration',
    loggedOut: 'Logged out of the admin panel',
  },
};
