import { CATEGORY } from './enums';

// Central UI copy used across pages and components — edit display text here,
// in one place, instead of hunting through the JSX. Dynamic messages are
// functions that take the values they interpolate.
export const STRINGS = {
  common: {
    brand: 'Rijisha Jewellers',
    logIn: 'Log In',
    startShopping: 'Start Shopping',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    freeShipping: 'Free',
    buyOnEtsy: 'Buy on Etsy',
    loaderDefault: 'Polishing the silver…',
    loginToWishlist: 'Please log in to save to wishlist',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    welcomeBack: (name) => `Welcome back, ${name}!`,
  },

  header: {
    announcements: [
      'Currently We accept orders from etsy only',
      'Handcrafted Elegance. Timelessly Yours. Designed Once. Owned Forever.',
      'Crafted Once. Never Repeated.',
    ],
    logoAlt: 'Rijisha Atelier — Handcrafted Elegance, Timelessly Yours',
    navHome: 'Home',
    navAbout: 'About',
    navShop: 'Shop',
    navRewards: 'My Rewards',
    navAdmin: 'Admin',
    hello: (name) => `Hi, ${name}`,
    loggedOut: 'You have been logged out',
  },

  footer: {
    about: 'Handcrafted 925 sterling silver earrings and necklaces — designed to be worn every day and treasured forever.',
    shopTitle: 'Shop',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    accountTitle: 'Account',
    aboutUs: 'About Us',
    myWishlist: 'My Wishlist',
    etsyShop: 'Our Etsy Shop',
    loginRegister: 'Login / Register',
    contactTitle: 'Contact Us',
    address: <>Rijisha Jewellers, 512 Hanuman Ji ka Rasta Tripolia Bazaar ,<br />Vishveshwarji Jaipur 302003</>,
    phone: '+91 98765 43210',
    email: 'rijishaenterprises@gmail.com',
    copyright: '© 2026 Rijisha Jewellers. All rights reserved.',
    tagline: 'Handcrafted with ♥ in India',
  },

  home: {
    heroEyebrow: 'Handcrafted 925 Sterling Silver Jewellery',
    heroTitle: <>Where Silver<br />Becomes <em>Poetry</em></>,
    heroText: 'Discover earrings and necklaces sculpted by master artisans — timeless silver jewellery designed to make every moment shine.',
    heroCtaShop: 'Shop Collection',
    heroCtaStory: 'Our Story',
    heroStats: [
      { value: '92.5%', label: 'Pure Silver' },
      { value: '5,000+', label: 'Happy Customers' },
      { value: '100%', label: 'Hallmarked' },
    ],
    heroVideoAria: 'Model flaunting Rijisha silver jewellery',
    collectionsEyebrow: 'Curated For You',
    collectionsTitle: 'Shop by Collection',
    collectionsText: 'Four signatures, one promise — silver that speaks softly and shines forever.',
    collectionSub: {
      [CATEGORY.EARRINGS]: 'Jhumkas · Hoops · Studs · Drops',
      [CATEGORY.NECKLACES]: 'Pendants · Chokers · Layered Chains',
      [CATEGORY.BRACELETS]: 'Bangles · Kadas · Charm Chains',
      [CATEGORY.ANTIQUE]: 'Anklets · Maang Tikkas · More',
    },
    comingSoonBadge: 'Coming Soon',
    comingSoonSub: 'Launching Soon · Stay Tuned',
    collectionAlt: (title) => `${title} collection`,
    featuredEyebrow: 'Bestsellers',
    featuredTitle: 'Our Signature Pieces',
    featuredText: 'Loved, reviewed and re-ordered — straight from the Rijisha atelier.',
    featuredLoader: 'Bringing out the bestsellers…',
    viewAll: 'View All Pieces',
    promises: [
      { title: '925 Sterling Silver', sub: 'BIS hallmarked purity' },
      { title: 'Handcrafted with Care', sub: 'Shaped by skilled artisans' },
      { title: 'Premium Rhodium-Plated Finish', sub: 'Long-lasting white lustre' },
      { title: 'Uniquely Crafted, Never Replicated', sub: 'No two pieces ever alike' },
    ],
    storyEyebrow: 'Our Story',
    storyMainAlt: 'A Rijisha silversmith shaping a pendant at the workbench',
    storyDetailAlt: 'Close-up of a finished sterling silver jhumka',
    storyBadge: <>Handmade<br /><b>in India</b></>,
    storyTitle: <>Crafted by Hand,<br />Cherished for Generations</>,
    storyText1: 'Rijisha Jewellers began as a small family atelier with one belief — that silver is not just a metal, but a memory in the making. Every piece we create carries the warmth of the hands that shaped it.',
    storyText2: 'Today, our master artisans blend traditional Indian karigari with contemporary design, creating earrings and necklaces that feel as personal as they look precious.',
    storyPoints: [
      'Handcrafted by third-generation silversmiths',
      'Ethically sourced, 92.5% pure sterling silver',
      'Premium Craftsmanship, Quality Assured',
    ],
    storyCta: 'Explore the Craft',
    testimonialsEyebrow: 'Words of Love',
    testimonialsTitle: 'What Our Customers Say',
    testimonialsText: 'Over 5,000 happy customers across India trust Rijisha for their silver moments.',
    testimonialsVia: 'via Etsy',
    instaEyebrow: 'On Instagram',
    instaTitle: 'As Worn By You',
    instaText: 'Tag @rijishaajewels to be featured — we love seeing our silver out in the world.',
    instaCta: 'Follow @rijishaajewels',
    testimonials: [
      {
        quote: '"The Meera Jhumkas are even more beautiful in person. The finish is flawless and they\'re so light I forget I\'m wearing them."',
        initials: 'AS',
        name: 'Ananya Sharma',
        city: 'Mumbai',
      },
      {
        quote: '"Bought the Tara layered necklace for my sister\'s wedding. Everyone asked where it was from. Packaging felt like a gift itself!"',
        initials: 'PR',
        name: 'Priya Raghavan',
        city: 'Bengaluru',
      },
      {
        quote: '"Six months of daily wear and my hoops still shine like day one. The anti-tarnish coating truly works. Fully worth it."',
        initials: 'MK',
        name: 'Meghna Kapoor',
        city: 'Delhi',
      },
    ],
  },

  shop: {
    eyebrow: 'The Collection',
    title: 'Shop Silver Jewellery',
    text: 'Every piece handcrafted in 92.5% sterling silver with an anti-tarnish finish.',
    allPieces: 'All Pieces',
    searchPlaceholder: 'Search jewellery...',
    sortFeatured: 'Featured',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortRating: 'Top Rated',
    sortNewest: 'Newest',
    soonPill: 'Coming Soon',
    soonTitle: 'Bracelets are on their way',
    soonText: 'Our artisans are crafting the very first Rijisha bracelet collection right now. Stay tuned — it will be worth the wait.',
    browseOther: 'Browse Other Pieces',
    loader: 'Laying out the collection…',
    noMatch: 'No pieces match your search.',
  },

  about: {
    eyebrow: 'About Us',
    title: 'THE HOUSE OF RIJISHA',
    intro: 'A family atelier in the old lanes of Jaipur, shaping 92.5% sterling silver into pieces meant to outlive the trends they were born in.',
    stats: [
      { value: '3', label: 'Generations of Silversmiths' },
      { value: '92.5%', label: 'Sterling Silver, Always' },
      { value: 'One Creation. One Chance.', label: 'Every Carved Piece' },
      { value: 'Jaipur', label: 'Handmade in India' },
    ],
    storyEyebrow: 'How It Began',
    storyTitle: <>From a Workbench<br />in Jaipur</>,
  storyParagraphs: [
  'At Rijisha Atelier, we believe jewellery is more than adornment—it is a story, a statement, and a timeless work of art. Every design is imagined, handcrafted, and released only once. Once a piece finds its owner, it becomes part of our archive, never to be recreated.',
  'Inspired by Jaipur\'s rich gemstone heritage, each creation begins with carefully selected natural gemstones whose beauty, character, and individuality shape the design itself. Handcrafted in 925 sterling silver, our jewellery blends traditional craftsmanship with contemporary elegance.',
  'Every piece is accompanied by a signed authenticity card, its unique piece number, and care instructions, making it a true one-of-one collectible. At Rijisha Atelier, you don\'t simply own jewellery—you own a creation that will never belong to anyone else.',
],
    storyPoints: [
      'Third-generation silversmiths, still at the bench',
      'Hand-carved stones — no moulds, no duplication',
      'Rhodium-finished and nickel-free, safe for daily wear',
    ],
    valuesEyebrow: 'What We Stand For',
    valuesTitle: 'Four Promises We Do Not Bend',
    valuesText: 'These are the rules the workshop runs on — the reasons a Rijisha piece costs what it costs and lasts as long as it does.',
    values: [
      {
        title: 'One of One',
        text: 'Each stone is carved by hand, so every piece carries its own grain, tone and character. We do not replicate a design once it has found its owner.',
      },
      {
        title: '925 and Nothing Less',
        text: 'Solid 92.5% sterling silver, hallmarked and nickel-free — never plated brass, never a silver-toned alloy standing in for the real thing.',
      },
      {
        title: 'Made by Hand',
        text: 'Carving, setting and polishing are all done at the bench by our own artisans. Slower than a machine, and the only way to get this finish.',
      },
      {
        title: 'Honest Pricing',
        text: 'You pay for the silver, the stone and the hours. No inflated MRP struck through to manufacture a discount that was never real.',
      },
    ],
    craftEyebrow: 'In the Workshop',
    craftTitle: 'How a Piece Comes to Be',
    craftText: 'From a rough stone to a finished pendant is roughly two weeks of work across four sets of hands.',
    craftSteps: [
      {
        title: 'Choosing the Stone',
        text: 'Rough gemstones are sorted by colour, clarity and character. Stones with a story in their grain are set aside for carving.',
      },
      {
        title: 'Hand Carving',
        text: 'The chosen stone is carved into its form — a leaf, a medallion, a tortoise shell. This is the slowest step and the one that cannot be repeated.',
      },
      {
        title: 'Setting in Silver',
        text: 'A solid 925 sterling silver frame is built around the finished stone, with claw or bezel detailing shaped to that specific piece.',
      },
      {
        title: 'Finish & Inspection',
        text: 'Rhodium plating for lasting lustre and tarnish resistance, a final hand polish, then a check against export standards before it is packed.',
      },
    ],
    visitEyebrow: 'Come Say Hello',
    visitTitle: 'Find Us in Jaipur',
    visitText: 'Orders are currently taken through our Etsy studio, and we are always happy to talk on WhatsApp about custom work, chains or gift packaging.',
    visitWhatsApp: 'Chat on WhatsApp',
    visitShop: 'Browse the Collection',
  },

  productCard: {
    addedToWishlist: (name) => `${name} added to wishlist`,
    removedFromWishlist: (name) => `${name} removed from wishlist`,
  },

  productDetail: {
    backToShop: 'Back to Shop',
    loader: 'Unveiling this piece…',
    crumbHome: 'Home',
    reviews: (rating, count) => `${rating} · ${count} reviews`,
    noReviews: 'No reviews yet',
    discountOff: (pct) => `${pct}% off`,
    taxNote: 'Inclusive of all taxes · Delivery in 5-7 days',
    points: [
      '92.5% pure sterling silver, BIS hallmarked',
      'Anti-tarnish e-coating for lasting shine',
      'Ships in premium gift packaging',
    ],
    onlyLeft: (n) => `Only ${n} left in stock`,
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    addedToWishlist: 'Added to wishlist',
    removedFromWishlist: 'Removed from wishlist',
    detailsTitle: 'Product Details',
    specMetal: 'Metal',
    specWeight: 'Weight',
    specPlating: 'Plating',
    specColor: 'Color',
    careInstructions: 'Care Instructions',
    packageContains: 'Package Contains',
    descriptionLabel: 'Description',
    soldBy: 'Sold by',
    countryOfOrigin: 'Country of Origin',
    // Store-wide fallbacks — a product may override either from the admin panel.
    defaultSoldBy: 'RIJISHA ENTERPRISES',
    defaultCountryOfOrigin: 'India',
    relatedEyebrow: 'Complete the Look',
    relatedTitle: 'You May Also Like',
    recentEyebrow: 'Pick Up Where You Left Off',
    recentTitle: 'Recently Viewed',
  },

  reviews: {
    eyebrow: 'From Our Customers',
    title: 'Ratings & Reviews',
    loader: 'Gathering customer stories…',
    empty: 'No reviews yet — be the first to share how this piece looks on you.',
    basedOn: (n) => `Based on ${n} review${n === 1 ? '' : 's'}`,
    writeTitle: 'Write a Review',
    yourRating: 'Your rating',
    ratingWords: ['', 'Poor', 'Fair', 'Good', 'Very good', 'Excellent'],
    commentLabel: 'Your review',
    commentPlaceholder: 'How is the shine, the finish, the fit? Share your experience…',
    photosLabel: 'Add photos (optional)',
    addPhotos: 'Add photos',
    photosHint: 'Up to 4 photos · JPG, PNG or WebP',
    maxPhotos: 'You can add up to 4 photos',
    removePhoto: 'Remove photo',
    submit: 'Post Review',
    submitting: 'Posting…',
    loginPrompt: 'Log in to review this piece',
    alreadyReviewed: 'You have already reviewed this piece — thank you!',
    posted: 'Thank you! Your review is live',
    deleted: 'Your review was removed',
    delete: 'Delete',
    youBadge: 'You',
    pickRating: 'Please pick a star rating',
    photoAlt: (name) => `Customer photo by ${name}`,
    // Photo-review reward (buy on Etsy → review with photo → 15% off next order)
    offerTitle: (pct) => `Get ${pct}% off your next Etsy order`,
    offerText: (pct) =>
      `Bought this on Etsy? Add a photo to your review and drop in your Etsy order number — we'll send you a ${pct}% off code for your next order once we've matched it. Any honest review counts.`,
    etsyOrderLabel: 'Etsy order number (to claim your discount)',
    etsyOrderPlaceholder: 'e.g. 3847592011',
    etsyOrderHint: 'Find it in your Etsy “Purchases and reviews” page. A photo is required to claim.',
    claimTitle: (pct) => `Claim your ${pct}% off`,
    claimText: 'Add your Etsy order number below and we’ll verify your purchase.',
    claimNeedsPhoto: 'Rewards need a photo — your review doesn’t have one, so it can’t be claimed.',
    claim: 'Claim discount',
    claiming: 'Claiming…',
    claimed: 'Reward claimed! We’ll verify your order and send your code.',
    rewardPending: 'Reward pending — we’re verifying your Etsy order.',
    rewardRejected: 'We couldn’t match this Etsy order number. Please double-check it on Etsy and try again.',
    retryTitle: 'Update your Etsy order number',
    retry: 'Try again',
    retried: 'Thanks! We’ll take another look at your order.',
    rewardCodeTitle: (pct) => `Your ${pct}% off code`,
    rewardCodeHint: 'Use this at checkout on Etsy for your next order.',
    copyCode: 'Copy',
    copied: 'Code copied',
  },

  rewards: {
    loginTitle: 'Log in to see your rewards',
    loginText: 'Your photo-review discounts live here.',
    eyebrow: 'Your Account',
    title: 'My Rewards',
    intro: (pct) => `Share a photo review of a piece you bought on Etsy and get ${pct}% off your next order.`,
    loader: 'Fetching your rewards…',
    empty: 'No rewards yet — add a photo to a review and enter your Etsy order number to claim one.',
    forPiece: (name) => `For ${name}`,
    orderNo: (no) => `Etsy order #${no}`,
    codeLabel: 'Your code',
    useOnEtsy: 'Use at checkout on Etsy',
    copyCode: 'Copy',
    copied: 'Code copied',
    browse: 'Browse Pieces',
    rejectedNote: 'We couldn’t match this Etsy order number. Double-check it on your Etsy purchases and re-submit below.',
    retryPlaceholder: 'Correct Etsy order number',
    retry: 'Try again',
    retrying: 'Submitting…',
    retried: 'Thanks! We’ll take another look at your order.',
    enterOrder: 'Please enter your Etsy order number',
    pendingNote: 'We’re verifying your Etsy order — your code will appear here once approved.',
  },

  cart: {
    emptyTitle: 'Your bag is empty',
    emptyText: 'Beautiful silver is waiting for you.',
    eyebrow: 'Your Bag',
    title: 'Shopping Bag',
    shipHint: (amount) => `Add ${amount} more for free shipping`,
    proceed: 'Proceed to Checkout',
    continueShopping: '← Continue shopping',
  },

  checkout: {
    loginTitle: 'Please log in to checkout',
    loginText: 'Your bag is saved — log in or create an account to place your order.',
    emptyTitle: 'Your bag is empty',
    eyebrow: 'Almost There',
    title: 'Checkout',
    shippingDetails: 'Shipping Details',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Your full name',
    phone: 'Phone',
    phonePlaceholder: '10-digit mobile number',
    phoneHint: 'Enter a 10-digit phone number',
    address: 'Address',
    addressPlaceholder: 'House no., street, area',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    pincodePlaceholder: '6-digit pincode',
    pincodeHint: 'Enter a 6-digit pincode',
    paymentMethod: 'Payment Method',
    codTitle: 'Cash on Delivery',
    codText: 'Pay when your order arrives',
    upiTitle: 'UPI',
    upiText: 'Pay on delivery via UPI',
    placing: 'Placing Order…',
    placeOrder: (amount) => `Place Order · ${amount}`,
    orderPlaced: 'Order placed successfully!',
  },

  orders: {
    loginTitle: 'Log in to see your orders',
    eyebrow: 'Your Account',
    title: 'My Orders',
    loader: 'Fetching your orders…',
    empty: "You haven't placed any orders yet.",
    orderNo: (id) => `Order #${id}`,
    shipsTo: (method, city, state, pincode) => `${method} · Ships to ${city}, ${state} ${pincode}`,
    total: (amount) => `Total: ${amount}`,
  },

  wishlist: {
    loginTitle: 'Log in to see your wishlist',
    loginText: 'Save the pieces you love and find them here anytime.',
    eyebrow: 'Saved With Love',
    title: 'My Wishlist',
    loader: 'Gathering your favourites…',
    empty: 'Nothing saved yet — tap the ♥ on any piece you love.',
    browse: 'Browse Pieces',
  },

  login: {
    eyebrow: 'Welcome Back',
    title: 'Log In',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    passwordPlaceholder: 'Your password',
    busy: 'Logging in…',
    switchText: 'New to Rijisha?',
    switchLink: 'Create an account',
    forgotLink: 'Forgot your password?',
  },

  forgotPassword: {
    eyebrow: 'Account Help',
    title: 'Forgot Password',
    intro: 'Enter the email you signed up with and we will send you a link to choose a new password.',
    submit: 'Send Reset Link',
    busy: 'Sending…',
    // Deliberately says nothing about whether the address has an account.
    sentTitle: 'Check your inbox',
    sentText: (email) =>
      `If ${email} has an account with us, a reset link is on its way. The link works for one hour.`,
    sentHint: 'Nothing after a few minutes? Check your spam folder, or try again.',
    backToLogin: 'Back to log in',
  },

  resetPassword: {
    eyebrow: 'Account Help',
    title: 'Choose a New Password',
    intro: (email) => `Setting a new password for ${email}.`,
    checking: 'Checking your link…',
    password: 'New Password',
    passwordPlaceholder: 'At least 6 characters',
    confirm: 'Confirm New Password',
    confirmPlaceholder: 'Type it once more',
    mismatch: 'Those two passwords do not match',
    submit: 'Update Password',
    busy: 'Updating…',
    done: 'Password updated — please log in.',
    invalidTitle: 'This link no longer works',
    invalidText: 'Reset links expire after an hour and can only be used once. Request a fresh one.',
    requestAgain: 'Request a new link',
  },

  register: {
    eyebrow: 'Join Us',
    title: 'Create Account',
    name: 'Full Name',
    namePlaceholder: 'Your name',
    passwordPlaceholder: 'At least 6 characters',
    busy: 'Creating account…',
    switchText: 'Already have an account?',
    switchLink: 'Log in',
    welcome: (name) => `Welcome to Rijisha, ${name}!`,
  },

  adminLogin: {
    eyebrow: 'Store Management',
    title: 'Admin Login',
    email: 'Admin Email',
    emailPlaceholder: 'admin@rijisha.com',
    passwordPlaceholder: 'Admin password',
    submit: 'Log In as Admin',
    note: 'This portal is for store administrators only.',
  },

  admin: {
    viewStore: '← View Store',
    signedInAs: (email) => `Signed in as ${email}`,
    logOut: 'Log Out',
    eyebrow: 'Store Management',
    title: 'Admin Panel',
    subtitle: 'Add, edit or remove pieces — changes appear on the shop instantly.',
    tabProducts: 'Products',
    tabHomepage: 'Homepage',
    tabRewards: 'Rewards',
    addProductBtn: '+ Add New Product',
    closeForm: 'Close',
    homepageMedia: 'Homepage Media',
    homepageMediaHint: 'Control what visitors see first — the hero video at the top of the home page and the photos on the four "Shop by Collection" cards. Reset anything to bring back its built-in default.',
    heroLabel: 'Hero Video — top of the home page',
    heroHelp: 'This video plays inside the arched frame of the hero section. A vertical (portrait) video looks best — mp4, webm or mov, up to 50 MB. Keep it short and seamless; it loops silently.',
    defaultTag: 'Default',
    uploading: 'Uploading…',
    changeVideo: 'Change Video',
    uploadVideo: 'Upload Video',
    resetToDefault: 'Reset to Default',
    collectionCardsLabel: 'Shop by Collection — card photos',
    changePhoto: 'Change Photo',
    uploadPhoto: 'Upload Photo',
    reset: 'Reset',
    editProduct: 'Edit Product',
    addNewProduct: 'Add New Product',
    nameLabel: 'Name *',
    namePlaceholder: 'e.g. Riya Silver Studs',
    categoryLabel: 'Category *',
    subCategoryLabel: 'Sub-category',
    subCategoryPlaceholder: 'e.g. Studs, Jhumka, Pendant',
    priceLabel: 'Price (₹) *',
    pricePlaceholder: '2499',
    mrpLabel: 'MRP (₹, for showing a discount)',
    mrpPlaceholder: '3199 (optional)',
    stockLabel: 'Stock',
    tagLabel: 'Tag',
    tagNone: 'None',
    mediaLabel: 'Photos & Videos (you can select multiple)',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Tell customers what makes this piece special...',
    metalLabel: 'Metal',
    metalPlaceholder: '92.5 Sterling Silver',
    weightLabel: 'Weight',
    weightPlaceholder: '10 g',
    platingLabel: 'Plating',
    platingPlaceholder: 'Rhodium Plating',
    colorLabel: 'Colour',
    colorPlaceholder: 'Green',
    soldByLabel: 'Sold by',
    soldByPlaceholder: 'RIJISHA ENTERPRISES',
    countryLabel: 'Country of Origin',
    countryPlaceholder: 'India',
    careLabel: 'Care Instructions',
    carePlaceholder: 'Avoid exposure to chemicals and handle with care...',
    packageLabel: 'Package Contains',
    packagePlaceholder: 'The package contains one pendant without chain',
    artStyleLabel: 'If no photo: illustration style',
    cardBackgroundLabel: 'Card background',
    previewLabel: 'Preview',
    mediaListLabel: (count) => `Product media (${count}) — the first photo is used as the thumbnail`,
    mediaNewTag: 'new',
    saving: 'Saving…',
    saveChanges: 'Save Changes',
    addProduct: 'Add Product',
    cancelEdit: 'Cancel Edit',
    allProducts: (count) => `All Products (${count})`,
    productSearchPlaceholder: 'Search by name or sub-category…',
    filterAllCategories: 'All categories',
    showingCount: (from, to, total) => `Showing ${from}–${to} of ${total}`,
    noProductsMatch: 'No products match your search.',
    clearSearch: 'Clear',
    prevPage: '← Prev',
    nextPage: 'Next →',
    pageOf: (page, total) => `Page ${page} of ${total}`,
    thName: 'Name',
    thCategory: 'Category',
    thPrice: 'Price',
    thStock: 'Stock',
    thTag: 'Tag',
    thActions: 'Actions',
    noTag: '—',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: (name) => `Delete "${name}"? This cannot be undone.`,
    productUpdated: 'Product updated',
    productAdded: 'Product added — it is live on the shop now',
    productDeleted: (name) => `${name} deleted`,
    heroUpdated: 'Hero video updated — it is live on the home page',
    photoUpdated: 'Collection photo updated — it is live on the home page',
    heroReset: 'Hero is back to the default video',
    cardReset: 'Card is back to its default illustration',
    loggedOut: 'Logged out of the admin panel',
    // Review rewards
    rewardsTitle: 'Review Rewards',
    rewardsHint: (pct) =>
      `Customers who post a photo review and enter their Etsy order number claim a ${pct}% off code. Verify the order number against your Etsy sales, then approve to send them the next code from your pool.`,
    couponPoolTitle: 'Coupon code pool',
    couponPoolStats: (available, used) => `${available} available · ${used} used`,
    couponPasteLabel: 'Paste 15%-off codes from your Etsy dashboard',
    couponPastePlaceholder: 'SILVER15-A7X2, SILVER15-B3K9, SILVER15-C8M4…',
    couponPasteHint: 'Separate codes with commas, spaces or new lines. Re-pasting is safe — duplicates are skipped.',
    couponAdd: 'Add to pool',
    couponAdding: 'Adding…',
    couponAdded: (n, skipped) => `Added ${n} code${n === 1 ? '' : 's'}${skipped ? ` · ${skipped} already in pool` : ''}`,
    couponEmpty: 'No codes yet — add some so you can approve rewards.',
    couponListTitle: 'Codes in the pool',
    couponListShow: 'Show codes',
    couponListHide: 'Hide codes',
    couponListCapped: (n) => `Showing the ${n} most recent codes.`,
    couponUsedTag: 'Sent',
    couponAvailableTag: 'Available',
    couponEdit: 'Edit',
    couponDelete: 'Delete',
    couponSave: 'Save',
    couponSaving: 'Saving…',
    couponCancel: 'Cancel',
    couponUpdated: (code) => `Code updated to ${code}`,
    couponDeleted: (code) => `${code} removed from the pool`,
    couponDeleting: 'Deleting…',
    couponConfirmDelete: 'Remove this code?',
    couponConfirmDeleteYes: 'Yes, remove',
    couponLockedHint: 'Sent codes cannot be edited or deleted.',
    rewardsLoader: 'Loading reward claims…',
    rewardsEmpty: 'No reward claims yet.',
    rewardNoPool: 'Add coupon codes to the pool before approving.',
    thCustomer: 'Customer',
    thEtsyOrder: 'Etsy order #',
    thReview: 'Review',
    thPhotos: 'Photos',
    thStatus: 'Status',
    approve: 'Approve',
    reject: 'Reject',
    approving: 'Approving…',
    rejecting: 'Rejecting…',
    rewardApproved: (code) => `Approved — code ${code} sent to the customer`,
    rewardRejected: 'Reward rejected',
    confirmReject: 'Reject this claim?',
    confirmRejectYes: 'Yes, reject',
    confirmRejectNo: 'Cancel',
    rewardCodeCol: 'Code',
  },

  whatsapp: {
    aria: 'Chat with us on WhatsApp',
    message: 'Hi Rijisha Jewellers! I have a question about your silver jewellery.',
  },

  notFound: {
    eyebrow: '404',
    title: 'This page has slipped off the chain',
    text: 'The page you are looking for does not exist or has been moved — but the silver is right where you left it.',
    home: 'Back to Home',
    shop: 'Browse the Shop',
  },

  titles: {
    home: 'Handcrafted 925 Silver Jewellery',
    about: 'About Us',
    shop: 'Shop Silver Jewellery',
    wishlist: 'My Wishlist',
    cart: 'Shopping Bag',
    checkout: 'Checkout',
    orders: 'My Orders',
    login: 'Log In',
    register: 'Create Account',
    forgotPassword: 'Forgot Password',
    resetPassword: 'Choose a New Password',
    adminLogin: 'Admin Login',
    admin: 'Admin Panel',
    rewards: 'My Rewards',
    notFound: 'Page Not Found',
  },
};
